# Generated by Django 3.1 on 2020-08-14 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
                ('descr_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
                ('descr_text', models.TextField()),
                ('number_text', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=1)),
                ('photo', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='frontend.location')),
            ],
        ),
    ]
